#services:
#  pgvector:
#    image: 'pgvector/pgvector:pg16'
#    environment:
#      - 'POSTGRES_DB=ChatBotRAG'
#      - 'POSTGRES_PASSWORD=yassineadmin'
#      - 'POSTGRES_USER=postgres'
#    labels:
#      - "org.springframework.boot.service-connection=postgres"
#    ports:
#      - '5432:5432'

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ChatBotRAG'
      - 'POSTGRES_PASSWORD=yassineadmin'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'